# Generated by Django 6.1 on 2026-08-31 16:22

from django.db import migrations


PERMISSIONS = (
    ("View dashboard", "dashboard.view", "View the central dashboard.", "dashboard", "view"),
    ("View users", "users.view", "List and view user accounts.", "users", "view"),
    ("Create users", "users.create", "Create user accounts.", "users", "create"),
    ("Update users", "users.update", "Edit accounts, roles, status, and reset passwords.", "users", "update"),
    ("Delete users", "users.delete", "Permanently delete user accounts.", "users", "delete"),
    ("View roles", "roles.view", "List roles and their assigned permissions.", "roles", "view"),
    ("Create roles", "roles.create", "Create new roles.", "roles", "create"),
    ("Update roles", "roles.update", "Edit roles and permission assignments.", "roles", "update"),
    ("Delete roles", "roles.delete", "Deactivate or permanently delete roles.", "roles", "delete"),
    ("View permissions", "permissions.view", "View the system permission registry.", "permissions", "view"),
    ("View settings", "settings.view", "View company and application settings.", "settings", "view"),
    ("Update settings", "settings.update", "Update company and application settings.", "settings", "update"),
)

ROLE_PERMISSIONS = {
    "ADMIN": tuple(item[1] for item in PERMISSIONS),
    "MANAGER": (
        "dashboard.view",
        "users.view",
        "users.create",
        "users.update",
        "roles.view",
        "permissions.view",
        "settings.view",
    ),
    "DATA_ENTRY": ("dashboard.view",),
}

ROLE_DESCRIPTIONS = {
    "ADMIN": "Full system administration. This role dynamically receives every active permission.",
    "MANAGER": "Operational user and role visibility with user-management access.",
    "DATA_ENTRY": "Restricted access suitable for future data-entry workflows.",
}


def seed_initial_authorization(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    Role = apps.get_model("accounts", "Role")
    permission_objects = {}
    for name, codename, description, module, action in PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            codename=codename,
            defaults={
                "name": name,
                "description": description,
                "module": module,
                "action": action,
                "is_active": True,
            },
        )
        permission_objects[codename] = permission

    for role_name, codenames in ROLE_PERMISSIONS.items():
        role, _ = Role.objects.update_or_create(
            name=role_name,
            defaults={
                "description": ROLE_DESCRIPTIONS[role_name],
                "is_active": True,
                "is_system": True,
            },
        )
        role.permissions.set(permission_objects[codename] for codename in codenames)


def keep_authorization_data(apps, schema_editor):
    # Authorization records may already be referenced by real users. A schema
    # rollback must not silently delete operational access-control data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_authorization, keep_authorization_data),
    ]
