# Generated by Django 5.2 on 2026-09-02 16:09

from django.db import migrations


def centralize_seeded_company_copy(apps, schema_editor):
    LandingSection = apps.get_model('website', 'LandingSection')
    LandingSection.objects.filter(
        key='home',
        title='Asanlink',
        subtitle='Connected products. One ecosystem.',
        description='A platform foundation for products and services that work together.',
    ).update(title='', subtitle='', description='')
    LandingSection.objects.filter(
        key='about',
        title='About Asanlink',
        description='Build, connect, and manage a growing ecosystem from one foundation.',
    ).update(title='Company', description='')


def preserve_managed_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_website_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='site_name',
        ),
        migrations.RunPython(centralize_seeded_company_copy, preserve_managed_copy),
    ]
