# Generated by Django 5.2 on 2026-09-02 16:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_websitesettings_site_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calltoaction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='website_cta_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='website_integration_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='landingsection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='website_landing_section_key_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='website_navigation_menu_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='website_product_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='website_product_category_slug_ci_unique'),
        ),
    ]
