# Generated by Django 5.2 on 2026-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_calltoaction_website_cta_slug_ci_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('location',), name='website_one_active_menu_per_location'),
        ),
    ]
