# Generated by Django 6.1 on 2026-09-01 16:54

import django.db.models.deletion
import finance.models
import finance.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('color', models.CharField(default='#61708a', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('AFN', 'Afghan afghani'), ('USD', 'US dollar')], max_length=3)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_occurrence', models.DateField()),
                ('project', models.CharField(blank=True, max_length=160)),
                ('product', models.CharField(blank=True, max_length=160)),
                ('payment_source', models.CharField(choices=[('COMPANY', 'Company funds'), ('PERSONAL', 'Personally paid')], default='COMPANY', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_occurrence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('AFN', 'Afghan afghani'), ('USD', 'US dollar')], max_length=3)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('project', models.CharField(blank=True, max_length=160)),
                ('product', models.CharField(blank=True, max_length=160)),
                ('receipt', models.FileField(blank=True, upload_to=finance.models.finance_upload_path, validators=[finance.validators.validate_finance_file])),
                ('notes', models.TextField(blank=True)),
                ('payment_source', models.CharField(choices=[('COMPANY', 'Company funds'), ('PERSONAL', 'Personally paid')], default='COMPANY', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('RECORDED', 'Recorded')], default='DRAFT', max_length=12)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('recurring_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='finance.recurringexpense')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('AFN', 'Afghan afghani'), ('USD', 'US dollar')], max_length=3)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PARTIAL', 'Partially settled'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OUTSTANDING', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlements_created', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlements_marked', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('AFN', 'Afghan afghani'), ('USD', 'US dollar')], max_length=3)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=finance.models.finance_upload_path, validators=[finance.validators.validate_finance_file])),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('VOIDED', 'Voided')], default='RECORDED', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contributions_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_contributions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contributions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['member', 'currency'], name='finance_con_member__547edb_idx'), models.Index(fields=['status', 'date'], name='finance_con_status_32bc67_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_contribution_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('RECORDED', 'Recorded')], max_length=12)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('RECORDED', 'Recorded')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expense_events', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finance.expense')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['expense', 'created_at'], name='finance_exp_expense_1f7e68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['is_active', 'next_occurrence'], name='finance_rec_is_acti_7320ff_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['currency', 'category'], name='finance_rec_currenc_0f6053_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_recurring_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['currency', 'date'], name='finance_exp_currenc_0278af_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'date'], name='finance_exp_status_f5c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'payment_source'], name='finance_exp_paid_by_afd8b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('occurrence_date__isnull', False), ('recurring_expense__isnull', False)), fields=('recurring_expense', 'occurrence_date'), name='finance_expense_recurring_occurrence_unique'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status', 'currency'], name='finance_set_status_b3e022_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payer', 'receiver'], name='finance_set_payer_i_ba4e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__gte', 0), ('settled_amount__lte', models.F('amount'))), name='finance_settlement_paid_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('payer', models.F('receiver')), _negated=True), name='finance_settlement_distinct_members'),
        ),
    ]
