"""System-owned authorization definitions.

Future modules extend this registry with additional database records; the
authorization engine itself does not need module-specific code.
"""

ADMIN_ROLE_NAME = "ADMIN"

PERMISSION_DEFINITIONS = (
    {
        "name": "View dashboard",
        "codename": "dashboard.view",
        "description": "View the central dashboard.",
        "module": "dashboard",
        "action": "view",
    },
    {
        "name": "View users",
        "codename": "users.view",
        "description": "List and view user accounts.",
        "module": "users",
        "action": "view",
    },
    {
        "name": "Create users",
        "codename": "users.create",
        "description": "Create user accounts.",
        "module": "users",
        "action": "create",
    },
    {
        "name": "Update users",
        "codename": "users.update",
        "description": "Edit accounts, roles, status, and reset passwords.",
        "module": "users",
        "action": "update",
    },
    {
        "name": "Delete users",
        "codename": "users.delete",
        "description": "Permanently delete user accounts.",
        "module": "users",
        "action": "delete",
    },
    {
        "name": "View roles",
        "codename": "roles.view",
        "description": "List roles and their assigned permissions.",
        "module": "roles",
        "action": "view",
    },
    {
        "name": "Create roles",
        "codename": "roles.create",
        "description": "Create new roles.",
        "module": "roles",
        "action": "create",
    },
    {
        "name": "Update roles",
        "codename": "roles.update",
        "description": "Edit roles and permission assignments.",
        "module": "roles",
        "action": "update",
    },
    {
        "name": "Delete roles",
        "codename": "roles.delete",
        "description": "Deactivate or permanently delete roles.",
        "module": "roles",
        "action": "delete",
    },
    {
        "name": "View permissions",
        "codename": "permissions.view",
        "description": "View the system permission registry.",
        "module": "permissions",
        "action": "view",
    },
    {
        "name": "View settings",
        "codename": "settings.view",
        "description": "View company and application settings.",
        "module": "settings",
        "action": "view",
    },
    {
        "name": "Update settings",
        "codename": "settings.update",
        "description": "Update company and application settings.",
        "module": "settings",
        "action": "update",
    },
    {
        "name": "View website CMS",
        "codename": "website.view",
        "description": "View public website content and configuration in the management system.",
        "module": "website",
        "action": "view",
    },
    {
        "name": "Manage website settings",
        "codename": "website.settings.manage",
        "description": "Manage general public website and footer settings.",
        "module": "website.settings",
        "action": "manage",
    },
    {
        "name": "Manage company information",
        "codename": "website.company.manage",
        "description": "Manage the public company profile.",
        "module": "website.company",
        "action": "manage",
    },
    {
        "name": "Manage website branding",
        "codename": "website.branding.manage",
        "description": "Manage public brand assets and theme tokens.",
        "module": "website.branding",
        "action": "manage",
    },
    {
        "name": "Manage website media",
        "codename": "website.media.manage",
        "description": "Upload and manage reusable public website media.",
        "module": "website.media",
        "action": "manage",
    },
    {
        "name": "Manage website navigation",
        "codename": "website.navigation.manage",
        "description": "Manage public navigation menus and items.",
        "module": "website.navigation",
        "action": "manage",
    },
    {
        "name": "Manage landing-page content",
        "codename": "website.landing.manage",
        "description": "Manage landing sections, features, and calls to action.",
        "module": "website.landing",
        "action": "manage",
    },
    {
        "name": "Manage website products",
        "codename": "website.products.manage",
        "description": "Manage public products, categories, features, and screenshots.",
        "module": "website.products",
        "action": "manage",
    },
    {
        "name": "Manage product integrations",
        "codename": "website.integrations.manage",
        "description": "Manage public ecosystem relationships between products.",
        "module": "website.integrations",
        "action": "manage",
    },
    {
        "name": "Manage website contacts",
        "codename": "website.contact.manage",
        "description": "Manage public contact details and communication channels.",
        "module": "website.contact",
        "action": "manage",
    },
    {
        "name": "Manage website SEO",
        "codename": "website.seo.manage",
        "description": "Manage site-wide and product search metadata.",
        "module": "website.seo",
        "action": "manage",
    },
    {
        "name": "View finance",
        "codename": "finance.view",
        "description": "View company finance dashboards and ledgers.",
        "module": "finance",
        "action": "view",
    },
    {
        "name": "Create expenses",
        "codename": "finance.expenses.create",
        "description": "Create company expense records.",
        "module": "finance.expenses",
        "action": "create",
    },
    {
        "name": "Edit expenses",
        "codename": "finance.expenses.edit",
        "description": "Edit draft or rejected expense records.",
        "module": "finance.expenses",
        "action": "edit",
    },
    {
        "name": "Submit expenses",
        "codename": "finance.expenses.submit",
        "description": "Submit expenses for approval.",
        "module": "finance.expenses",
        "action": "submit",
    },
    {
        "name": "Approve expenses",
        "codename": "finance.expenses.approve",
        "description": "Approve submitted expenses.",
        "module": "finance.expenses",
        "action": "approve",
    },
    {
        "name": "Reject expenses",
        "codename": "finance.expenses.reject",
        "description": "Reject submitted expenses with a reason.",
        "module": "finance.expenses",
        "action": "reject",
    },
    {
        "name": "Record expense payments",
        "codename": "finance.expenses.record",
        "description": "Mark approved expenses as paid or recorded.",
        "module": "finance.expenses",
        "action": "record",
    },
    {
        "name": "Create contributions",
        "codename": "finance.contributions.create",
        "description": "Record founder and member contributions.",
        "module": "finance.contributions",
        "action": "create",
    },
    {
        "name": "Edit contributions",
        "codename": "finance.contributions.edit",
        "description": "Edit or void contribution records.",
        "module": "finance.contributions",
        "action": "edit",
    },
    {
        "name": "View settlements",
        "codename": "finance.settlements.view",
        "description": "View member balances and settlement recommendations.",
        "module": "finance.settlements",
        "action": "view",
    },
    {
        "name": "Record settlements",
        "codename": "finance.settlements.settle",
        "description": "Record and mark member settlements as paid.",
        "module": "finance.settlements",
        "action": "settle",
    },
    {
        "name": "View finance reports",
        "codename": "finance.reports.view",
        "description": "View finance reports and cash-flow analysis.",
        "module": "finance.reports",
        "action": "view",
    },
    {
        "name": "Export finance reports",
        "codename": "finance.reports.export",
        "description": "Export filtered finance data as CSV or PDF.",
        "module": "finance.reports",
        "action": "export",
    },
    {
        "name": "Manage recurring expenses",
        "codename": "finance.recurring.manage",
        "description": "Create, pause, edit, and generate recurring expenses.",
        "module": "finance.recurring",
        "action": "manage",
    },
)

DEFAULT_ROLE_PERMISSIONS = {
    "ADMIN": tuple(item["codename"] for item in PERMISSION_DEFINITIONS),
    "MANAGER": (
        "dashboard.view",
        "users.view",
        "users.create",
        "users.update",
        "roles.view",
        "permissions.view",
        "settings.view",
        "website.view",
        "finance.view",
        "finance.expenses.create",
        "finance.expenses.edit",
        "finance.expenses.submit",
        "finance.contributions.create",
        "finance.contributions.edit",
        "finance.settlements.view",
        "finance.reports.view",
        "finance.reports.export",
        "finance.recurring.manage",
    ),
    "DATA_ENTRY": (
        "dashboard.view",
        "finance.view",
        "finance.expenses.create",
        "finance.expenses.submit",
        "finance.contributions.create",
    ),
}

DEFAULT_ROLE_DESCRIPTIONS = {
    "ADMIN": "Full system administration. This role dynamically receives every active permission.",
    "MANAGER": "Operational user and role visibility with user-management access.",
    "DATA_ENTRY": "Restricted access suitable for future data-entry workflows.",
}
