export const publicationChoices = [
  ['draft', 'Draft'],
  ['published', 'Published'],
  ['archived', 'Archived'],
]

export const assetField = (name, label, extra = {}) => ({
  name: `${name}_id`,
  label,
  type: 'select',
  optionResource: 'media-assets',
  optionValue: 'id',
  optionLabel: (item) => `${item.title} (${item.kind})`,
  getValue: (item) => item?.[name]?.id || '',
  nullable: true,
  ...extra,
})

export const configDefinitions = {
  settings: {
    endpoint: 'settings',
    title: 'General settings',
    description: 'Site identity, language, and optional public announcement.',
    permission: 'website.settings.manage',
    fields: [
      { name: 'default_language', label: 'Default language', required: true },
      { name: 'announcement_text', label: 'Announcement text', full: true },
      { name: 'announcement_url', label: 'Announcement link', full: true },
      { name: 'show_announcement', label: 'Show announcement', type: 'checkbox', full: true },
    ],
  },
  company: {
    endpoint: 'company',
    title: 'Company information',
    description: 'The single source for company identity used throughout the public site.',
    permission: 'website.company.manage',
    fields: [
      { name: 'name', label: 'Company name', required: true },
      { name: 'legal_name', label: 'Legal name' },
      { name: 'tagline', label: 'Tagline', full: true },
      { name: 'short_description', label: 'Short description', type: 'textarea', full: true },
      { name: 'long_description', label: 'Long description', type: 'textarea', rows: 6, full: true },
      { name: 'website', label: 'Website', type: 'url' },
      { name: 'founded_year', label: 'Founded year', type: 'number', nullable: true },
      { name: 'copyright_text', label: 'Copyright text', full: true },
    ],
  },
  branding: {
    endpoint: 'branding',
    title: 'Branding and theme tokens',
    description: 'Central color and asset values consumed as public CSS variables.',
    permission: 'website.branding.manage',
    fields: [
      { name: 'primary_color', label: 'Primary color', type: 'color', required: true },
      { name: 'secondary_color', label: 'Secondary color', type: 'color', required: true },
      { name: 'accent_color', label: 'Accent color', type: 'color', required: true },
      { name: 'background_color', label: 'Background color', type: 'color', required: true },
      { name: 'text_color', label: 'Text color', type: 'color', required: true },
      { name: 'dark_primary_color', label: 'Dark primary', type: 'color', required: true },
      { name: 'dark_secondary_color', label: 'Dark secondary', type: 'color', required: true },
      { name: 'dark_accent_color', label: 'Dark accent', type: 'color', required: true },
      { name: 'dark_background_color', label: 'Dark background', type: 'color', required: true },
      { name: 'dark_text_color', label: 'Dark text', type: 'color', required: true },
      assetField('logo', 'Primary logo'),
      assetField('dark_logo', 'Dark-mode logo'),
      assetField('favicon', 'Favicon'),
    ],
  },
  contact: {
    endpoint: 'contact-settings',
    title: 'Primary contact information',
    description: 'Canonical company contact details; extra methods are managed as channels below.',
    permission: 'website.contact.manage',
    fields: [
      { name: 'contact_title', label: 'Contact heading' },
      { name: 'contact_description', label: 'Contact description', type: 'textarea', full: true },
      { name: 'general_email', label: 'General email', type: 'email' },
      { name: 'sales_email', label: 'Sales email', type: 'email' },
      { name: 'support_email', label: 'Support email', type: 'email' },
      { name: 'primary_phone', label: 'Primary phone', type: 'tel' },
      { name: 'address_line_1', label: 'Address line 1', full: true },
      { name: 'address_line_2', label: 'Address line 2', full: true },
      { name: 'city', label: 'City' },
      { name: 'region', label: 'Region / province' },
      { name: 'country', label: 'Country' },
      { name: 'postal_code', label: 'Postal code' },
      { name: 'business_hours', label: 'Business hours', type: 'textarea', full: true },
    ],
  },
  seo: {
    endpoint: 'seo',
    title: 'Search and social metadata',
    description: 'Default browser, search-engine, canonical, and Open Graph values.',
    permission: 'website.seo.manage',
    fields: [
      { name: 'site_title', label: 'Site title', required: true, full: true },
      { name: 'meta_description', label: 'Meta description', type: 'textarea', full: true },
      { name: 'keywords', label: 'Keywords', type: 'json', hint: 'JSON list, for example ["platform", "software"]', full: true, jsonEmptyValue: [] },
      { name: 'open_graph_title', label: 'Open Graph title', full: true },
      { name: 'open_graph_description', label: 'Open Graph description', type: 'textarea', full: true },
      { name: 'canonical_url', label: 'Canonical URL', type: 'url', full: true },
      { name: 'robots', label: 'Robots directive', full: true },
      assetField('open_graph_image', 'Open Graph image', { full: true }),
    ],
  },
  footer: {
    endpoint: 'footer',
    title: 'Footer settings',
    description: 'Visibility and reusable footer content; links come from footer navigation menus.',
    permission: 'website.settings.manage',
    fields: [
      { name: 'is_visible', label: 'Show footer', type: 'checkbox' },
      { name: 'show_logo', label: 'Show company logo', type: 'checkbox' },
      { name: 'show_navigation', label: 'Show footer navigation', type: 'checkbox' },
      { name: 'show_social_links', label: 'Show social channels', type: 'checkbox' },
      { name: 'legal_text', label: 'Additional legal text', type: 'textarea', full: true },
    ],
  },
}

export const resourceDefinitions = {
  media: {
    resource: 'media-assets', title: 'Media library', singular: 'media asset', permission: 'website.media.manage',
    description: 'Upload reusable assets once, then associate them with content.', titleField: 'title',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'alt_text', label: 'Alternative text' },
      { name: 'kind', label: 'Asset type', type: 'select', required: true, choices: [['image', 'Image'], ['logo', 'Logo'], ['icon', 'Icon'], ['favicon', 'Favicon'], ['document', 'Document']], default: 'image' },
      { name: 'file', label: 'File', type: 'file', requiredOnCreate: true, full: true },
      { name: 'is_public', label: 'Publicly available', type: 'checkbox', default: true, full: true },
    ],
    summary: (item) => item.original_name || item.kind,
  },
  menus: {
    resource: 'navigation-menus', title: 'Navigation menus', singular: 'menu', permission: 'website.navigation.manage',
    description: 'Define independent header, footer, and utility menus.', titleField: 'name',
    fields: [
      { name: 'name', label: 'Menu name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'location', label: 'Location', type: 'select', required: true, choices: [['header', 'Header'], ['footer', 'Footer'], ['utility', 'Utility']], default: 'header' },
      { name: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.location} · ${item.items_count || 0} items`,
  },
  navigationItems: {
    resource: 'navigation-items', title: 'Navigation items', singular: 'navigation item', permission: 'website.navigation.manage',
    description: 'Set destinations, nesting, visibility, and order.', titleField: 'label', ordered: true,
    fields: [
      { name: 'menu_id', label: 'Menu', type: 'select', optionResource: 'navigation-menus', optionLabel: (item) => item.name, getValue: (item) => item.menu?.id || '', required: true },
      { name: 'parent_id', label: 'Parent item', type: 'select', optionResource: 'navigation-items', optionLabel: (item) => item.label, getValue: (item) => item.parent?.id || '', nullable: true },
      { name: 'label', label: 'Label', required: true },
      { name: 'link_type', label: 'Link type', type: 'select', choices: [['internal', 'Internal route / anchor'], ['external', 'External URL']], default: 'internal', required: true },
      { name: 'internal_path', label: 'Internal path or anchor' },
      { name: 'external_url', label: 'External URL', type: 'url' },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'open_in_new_tab', label: 'Open in new tab', type: 'checkbox' },
      { name: 'is_enabled', label: 'Enabled', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.menu?.name || ''} · ${item.href || 'No destination'}`,
  },
  ctas: {
    resource: 'ctas', title: 'Calls to action', singular: 'CTA', permission: 'website.landing.manage',
    description: 'Reusable CTA copy and button destinations.', titleField: 'name', ordered: true, publishable: true,
    fields: [
      { name: 'name', label: 'Internal name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'title', label: 'Public title', full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'primary_label', label: 'Primary button text' },
      { name: 'primary_url', label: 'Primary button URL' },
      { name: 'secondary_label', label: 'Secondary button text' },
      { name: 'secondary_url', label: 'Secondary button URL' },
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => item.title || item.slug,
  },
  sections: {
    resource: 'landing-sections', title: 'Landing-page sections', singular: 'section', permission: 'website.landing.manage',
    description: 'Enable, disable, and order supported structured page sections.', titleField: 'title', ordered: true, publishable: true,
    fields: [
      { name: 'key', label: 'Unique key / anchor', required: true },
      { name: 'section_type', label: 'Section type', type: 'select', required: true, choices: [['hero', 'Hero'], ['about', 'About / company'], ['products', 'Products'], ['features', 'Features / benefits'], ['integrations', 'Integrations / ecosystem'], ['cta', 'Call to action'], ['contact', 'Contact'], ['custom', 'Custom structured content']] },
      { name: 'title', label: 'Title', full: true },
      { name: 'subtitle', label: 'Subtitle', full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      assetField('image', 'Section image'),
      { name: 'call_to_action_id', label: 'CTA', type: 'select', optionResource: 'ctas', optionLabel: (item) => item.name, getValue: (item) => item.call_to_action?.id || '', nullable: true },
      { name: 'content', label: 'Structured content', type: 'json', hint: 'JSON object for renderer-specific values.', full: true, default: '{}' },
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.section_type} · #${item.key}`,
  },
  features: {
    resource: 'features', title: 'Features and benefits', singular: 'feature', permission: 'website.landing.manage',
    description: 'Reusable benefit cards attached to a features section.', titleField: 'title', ordered: true, publishable: true,
    fields: [
      { name: 'section_id', label: 'Features section', type: 'select', optionResource: 'landing-sections', optionLabel: (item) => item.title || item.key, optionFilter: (item) => item.section_type === 'features', getValue: (item) => item.section?.id || '', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'icon_name', label: 'Icon label / key' },
      assetField('icon', 'Icon asset'),
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => item.section?.title || item.section?.key,
  },
  categories: {
    resource: 'product-categories', title: 'Product categories', singular: 'category', permission: 'website.products.manage',
    description: 'Group products without hardcoding taxonomy in React.', titleField: 'name', ordered: true, publishable: true,
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => item.slug,
  },
  products: {
    resource: 'products', title: 'Products', singular: 'product', permission: 'website.products.manage',
    description: 'Publish and order any current or future ecosystem product.', titleField: 'name', ordered: true, publishable: true,
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'category_id', label: 'Category', type: 'select', optionResource: 'product-categories', optionLabel: (item) => item.name, getValue: (item) => item.category?.id || '', nullable: true },
      { name: 'short_description', label: 'Short description', type: 'textarea', full: true },
      { name: 'full_description', label: 'Full description', type: 'textarea', rows: 7, full: true },
      assetField('logo', 'Logo / icon'),
      assetField('cover_image', 'Cover / hero image'),
      { name: 'product_url', label: 'Product URL', type: 'url', full: true },
      { name: 'cta_label', label: 'CTA text' },
      { name: 'cta_url', label: 'CTA URL' },
      { name: 'technical_information', label: 'Technical / integration information', type: 'json', hint: 'JSON object.', full: true, default: '{}' },
      { name: 'seo_title', label: 'SEO title', full: true },
      { name: 'seo_description', label: 'SEO description', type: 'textarea', full: true },
      { name: 'seo_keywords', label: 'SEO keywords', type: 'json', hint: 'JSON list of strings.', full: true, default: '[]', jsonEmptyValue: [] },
      { name: 'canonical_url', label: 'Canonical URL', type: 'url', full: true },
      assetField('open_graph_image', 'Open Graph image'),
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => item.category?.name || item.slug,
  },
  productFeatures: {
    resource: 'product-features', title: 'Product feature lists', singular: 'product feature', permission: 'website.products.manage',
    description: 'Short, ordered feature points displayed with products.', titleField: 'title', ordered: true,
    fields: [
      { name: 'product_id', label: 'Product', type: 'select', optionResource: 'products', optionLabel: (item) => item.name, getValue: (item) => item.product?.id || '', required: true },
      { name: 'title', label: 'Feature', required: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => item.product?.name,
  },
  productMedia: {
    resource: 'product-media', title: 'Product screenshots and media', singular: 'product media', permission: 'website.products.manage',
    description: 'Associate reusable media assets with product galleries.', titleField: (item) => item.asset?.title || 'Media', ordered: true,
    fields: [
      { name: 'product_id', label: 'Product', type: 'select', optionResource: 'products', optionLabel: (item) => item.name, getValue: (item) => item.product?.id || '', required: true },
      { name: 'asset_id', label: 'Media asset', type: 'select', optionResource: 'media-assets', optionLabel: (item) => item.title, getValue: (item) => item.asset?.id || '', required: true },
      { name: 'kind', label: 'Placement type', type: 'select', choices: [['screenshot', 'Screenshot'], ['gallery', 'Gallery image'], ['diagram', 'Technical diagram']], default: 'screenshot', required: true },
      { name: 'caption', label: 'Caption', full: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.product?.name || ''} · ${item.kind}`,
  },
  integrations: {
    resource: 'integrations', title: 'Product integrations', singular: 'integration', permission: 'website.integrations.manage',
    description: 'Model directional or bidirectional relationships between any products.', titleField: 'name', ordered: true, publishable: true,
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'source_product_id', label: 'Source product', type: 'select', optionResource: 'products', optionLabel: (item) => item.name, getValue: (item) => item.source_product?.id || '', required: true },
      { name: 'destination_product_id', label: 'Destination product', type: 'select', optionResource: 'products', optionLabel: (item) => item.name, getValue: (item) => item.destination_product?.id || '', required: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'integration_type', label: 'Integration type key', default: 'api', required: true },
      { name: 'operational_status', label: 'Integration status', type: 'select', choices: [['planned', 'Planned'], ['active', 'Active'], ['paused', 'Paused'], ['deprecated', 'Deprecated']], default: 'planned', required: true },
      { name: 'is_bidirectional', label: 'Bidirectional', type: 'checkbox' },
      assetField('icon', 'Icon'),
      { name: 'documentation_url', label: 'Documentation URL', type: 'url', full: true },
      { name: 'api_information', label: 'API / integration information', type: 'json', hint: 'JSON object. Only published integration data is public.', full: true, default: '{}' },
      { name: 'status', label: 'Publication status', type: 'select', choices: publicationChoices, default: 'draft', required: true },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.source_product?.name || ''} ${item.is_bidirectional ? '↔' : '→'} ${item.destination_product?.name || ''}`,
  },
  contactChannels: {
    resource: 'contact-channels', title: 'Additional contact channels', singular: 'contact channel', permission: 'website.contact.manage',
    description: 'Add social accounts, WhatsApp, messaging, phone, hours, and future methods.', titleField: 'label', ordered: true,
    fields: [
      { name: 'channel_type', label: 'Channel type', type: 'select', required: true, choices: [['email', 'Email'], ['phone', 'Phone'], ['address', 'Address'], ['social', 'Social media'], ['messaging', 'Messaging'], ['hours', 'Business hours'], ['other', 'Other']] },
      { name: 'label', label: 'Label', required: true },
      { name: 'value', label: 'Displayed value', required: true, full: true },
      { name: 'url', label: 'Link', full: true },
      { name: 'icon_name', label: 'Icon label / key' },
      assetField('icon', 'Icon asset'),
      { name: 'display_order', label: 'Display order', type: 'number', default: 0, required: true },
      { name: 'is_visible', label: 'Visible', type: 'checkbox', default: true },
    ],
    summary: (item) => `${item.channel_type} · ${item.value}`,
  },
}
